language: node_js
node_js:
  - "0.10"

before_install:
  - sudo apt-get update 

install:
  # node-canvas dependency
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

  # install grunt-cli
  - npm install -g grunt-cli
  - cd utils

  # install dependencies
  - npm install .

script:
  - grunt build
