name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ${{ matrix.ros_distro }} (node ${{ matrix.node_version }})
    if: ${{ github.actor != 'RWT-bot' }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-core
      options: --cap-add=SYS_ADMIN
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [noetic]
        node_version: [16, 18, 20]
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - name: Install git in container
        run: |
          apt-get update
          apt-get install -q -y git
      - name: Set git safe directory
        run: |
          git config --global safe.directory '*'
      - uses: actions/checkout@v3
        env:
          TOKEN: "${{ github.event_name == 'push' && endsWith(github.ref, 'develop') && matrix.ros_distro == 'noetic' && secrets.RWT_BOT_PAT || github.token }}"
        with:
          token: ${{ env.TOKEN }}
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}
      - name: Own /github/home and PWD
        run: |
          chown -hR 1001:121 /github/home .
      - name: Install apt dependencies
        run: |
          apt-get install -q -y libasound2 libnss3 ros-$ROS_DISTRO-rosbridge-server ros-$ROS_DISTRO-tf2-web-republisher ros-$ROS_DISTRO-common-tutorials ros-$ROS_DISTRO-rospy-tutorials ros-$ROS_DISTRO-actionlib-tutorials
      - name: Tests
        run: |
          bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && bash test/build.bash"
      - name: Commit update of build
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'push' && endsWith(github.ref, 'develop') && matrix.ros_distro == 'noetic' && matrix.node_version == 18 }}
        with:
          commit_message: Update Build
          file_pattern: 'build/*.js'
